import { chromium, launchOptions, artifactPath } from './browser-runtime.mjs';
import assert from 'node:assert/strict';
const browser = await chromium.launch(launchOptions);
try {
 const page=await browser.newPage({viewport:{width:1280,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:41732');await page.click('#welcomeNewButton');
 await page.evaluate(async()=>{const {EditorView}=await import('/node_modules/@codemirror/view/dist/index.js');window.v=EditorView.findFromDOM(document.querySelector('.cm-content'));});
 const source='# 写作验收\n\n正文 **重点**。\n\n| A | B |\n| --- | --- |\n| x | y |\n\n> [!note] 标题\n> 内容\n\n尾段';
 await page.evaluate(s=>v.dispatch({changes:{from:0,to:v.state.doc.length,insert:s},selection:{anchor:5}}),source);
 const get=()=>page.evaluate(()=>v.state.doc.toString());
 assert.equal(await page.locator('#sourceToggle').count(),0);
 const selection=await page.evaluate(()=>v.state.selection.main.head);
 await page.click('#readingToggle');await page.locator('[data-mode=source]').click();
 assert.equal(await page.locator('.leaf-table-widget').count(),0);
 assert.equal(await page.locator('.leaf-callout-widget').count(),0);
 assert.equal(await get(),source);assert.equal(await page.evaluate(()=>v.state.selection.main.head),selection);
 await page.evaluate(()=>{v.dispatch({selection:{anchor:v.state.doc.length}});v.focus();});
 await page.keyboard.type('!');await page.click('#readingToggle');await page.locator('[data-mode=edit]').click();
 assert.equal(await get(),source+'!');await page.click('#undoButton');assert.equal(await get(),source);
 await page.evaluate(()=>{v.dispatch({selection:{anchor:v.state.doc.length}});v.focus();});
 await page.keyboard.insertText('网站');
 await page.keyboard.press('Shift+ArrowLeft');await page.keyboard.press('Shift+ArrowLeft');
 await page.keyboard.press('ControlOrMeta+k');
 assert.equal(await page.locator('.leaf-writing-dialog').count(),0);
 assert.equal(await page.evaluate(()=>v.state.doc.sliceString(v.state.selection.main.from,v.state.selection.main.to)),'链接地址');
 await page.keyboard.insertText('https://example.com');assert.ok((await get()).endsWith('[网站](https://example.com)'));
 await page.keyboard.press('ControlOrMeta+k');
 assert.equal(await page.evaluate(()=>v.state.doc.sliceString(v.state.selection.main.from,v.state.selection.main.to)),'https://example.com');
 assert.equal(await page.locator('.leaf-writing-dialog').count(),0);
 await page.click('#undoButton');await page.click('#undoButton');await page.click('#undoButton');assert.equal(await get(),source);
 await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=>'<b>literal</b>',write:async items=>window.richItems=items}});v.dispatch({selection:{anchor:v.state.doc.length}});v.focus();});
 await page.click('#commandsButton');await page.fill('#paletteInput','粘贴为纯文本');await page.keyboard.press('Enter');assert.ok((await get()).endsWith('<b>literal</b>'));await page.click('#undoButton');assert.equal(await get(),source);
 await page.click('#commandsButton');await page.fill('#paletteInput','复制为富文本');await page.keyboard.press('Enter');await page.waitForFunction(()=>window.richItems?.length);
 const rich=await page.evaluate(async()=>({html:await (await richItems[0].getType('text/html')).text(),plain:await (await richItems[0].getType('text/plain')).text()}));
 assert.ok(rich.html.includes('<strong>重点</strong>'));assert.equal(rich.plain,source);
 const converted=await page.evaluate(async()=>{const {htmlToMarkdown}=await import('/src/html-markdown.js');return htmlToMarkdown('<h2>标题</h2><p><strong>重点</strong> <a href="javascript:alert(1)">安全文本</a></p><pre>a\n\n\nb</pre><table><tr><th>A</th><th>B</th></tr><tr><td>甲</td><td>乙</td></tr></table><script>window.pwned=1</script>');});
 assert.ok(converted.includes('## 标题'));assert.ok(converted.includes('**重点**'));assert.ok(converted.includes('a\n\n\nb'));assert.ok(converted.includes('| 甲 | 乙 |'));assert.ok(!converted.includes('javascript'));assert.ok(!converted.includes('pwned'));
 await page.evaluate(()=>{v.dispatch({selection:{anchor:v.state.doc.length}});v.focus();const data=new DataTransfer();data.setData('text/html','<p><strong>粘贴</strong>正文</p>');data.setData('text/plain','粘贴正文');document.querySelector('.cm-content').dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));});
 assert.ok((await get()).endsWith('**粘贴**正文'));await page.click('#undoButton');assert.equal(await get(),source);
 await page.evaluate(async()=>{
  const {setResourceReader}=await import('/src/resources.js');
  const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
  setResourceReader(async path=>{if(path==='assets/missing.png')throw Error('missing');return Array.from(atob(png),c=>c.charCodeAt(0));});
  v.dispatch({changes:{from:0,to:v.state.doc.length,insert:'# 图片\n\n![替代文字](assets/photo.png)\n\n尾段'},selection:{anchor:0}});
 });
 await page.waitForSelector('img[data-loaded="yes"]');
 await page.locator('#readingToggle').click();await page.locator('.mode-popover [data-mode='+((await page.locator('#readingPane').isVisible())?'edit':'reading')+']').click();await page.waitForSelector('.reading-document img[data-loaded="yes"]');
 assert.equal(await page.locator('.reading-document img').getAttribute('alt'),'替代文字');
 await page.locator('#readingToggle').click();await page.locator('.mode-popover [data-mode='+((await page.locator('#readingPane').isVisible())?'edit':'reading')+']').click();
 await page.setViewportSize({width:650,height:700});
 await page.emulateMedia({colorScheme:'dark'});
 await page.click('#linkInsert');
 assert.equal(await page.locator('.leaf-writing-dialog').count(),0);
 await page.keyboard.press('Escape');assert.equal(await page.locator('.leaf-writing-dialog').count(),0);
 const fieldShortcut=await page.evaluate(()=>{const input=document.createElement('input');document.body.append(input);input.focus();const e=new KeyboardEvent('keydown',{key:'t',metaKey:true,bubbles:true,cancelable:true});input.dispatchEvent(e);input.remove();return e.defaultPrevented;});
 assert.equal(fieldShortcut,false,'writing shortcuts must not steal input-field editing');
 await page.evaluate(()=>{Object.defineProperty(navigator.clipboard,'readText',{configurable:true,value:async()=> '纯文本快捷键测试'});document.querySelector('.cm-content').dispatchEvent(new KeyboardEvent('keydown',{key:'t',metaKey:true,bubbles:true,cancelable:true}));});
 await page.waitForFunction(()=>document.querySelector('.cm-content').textContent.includes('纯文本快捷键测试'));
 await page.screenshot({path:artifactPath('leaf-writing-images.png')});
 assert.deepEqual(errors,[]);console.log('PASS source mode shared undo, links, rich paste, code whitespace, safe targets and shared image rendering');
} finally {await browser.close();}
